language: python
python:
- '3.4'
cache: apt
install:
- 'pip install -r requirements.txt'
script: make html
notifications:
  email:
    on_failure: always
deploy:
  provider: s3
  access_key_id: AKIAI3ZT6IVTGI6K5NQQ
  secret_access_key: 
   secure: LUIprU2Lvrgi2IbVCXBKa2KzXNL6YPsaUVJe8/KOUa1IRBMAHZ7Rbkws1ynFn6q00OsSpyVNu/E2wFUonyoZ7Zc5hsOd6Ph44qjZt9TaxRti42AHdQWPUVECYvHq+r2oIkNDgX/uRT0lxcE3Xz07KlxFu5wSECjWxQBj6D8GH14+b8rq8v71HBUcSewN43wtsQ1Cm7mcTL9Bv54UczFmwObycB/bbTZNnLire+PhXRr2ZZZvonDUfacVUfQotjALrvi8ukHmoVfR2FkGsUgGL6TjIndqA2n5BaK9DofI1Plq4gmq1rnjAavj0nX8WXJQ5zPzGuLZLL51yrOPOegkkQ==
  bucket: www.phillustration.net
  endpoint: www.phillustration.net.s3-website-us-east-1.amazonaws.com 
  acl: public_read
  region: us-east-1
  skip_cleanup: true
  local_dir: output
  detect_encoding: true
  on:
    repo: HandyCodeJob/phillustration
